= Cadena de Mando
:toc:
:toclevels: 3
:toc-title: Contenido

WARNING: Borrador en desarrollo.

_A diferencia de otros juegos de estrategia donde las unidades se pueden mover libremente por el campo de batalla, las reglas de AoW han sido diseñadas para reflejar la estructura de combate de las unidades dentro de la Segunda Guerra Mundial donde las escuadras no operan independientemente conociendo la situación del campo de batalla. Para que una unidad que estaba defendiendo una posición pueda lanzar un ataque será necesario que un oficial haya transmitido esa orden. La pérdida de los oficiales implicará severas penalizaciones a la capacidad combativa del resto de unidades._

== Estructura de mando

Normalmente a la escala del juego que seriá por compañias donde tendremos un jefe de compañía (rango Capitán), varios jefes de sección (rango Teniente/Sargento) y varios jefes de escuadra (rango Cabo).

El grado de organización de cada una de las compañías estará afectado por el estado de la cadena de mando. Por ejemplo, si el jefe de una sección resulta eliminado las escuadras bajo su mando sufrirán una penalización en la recuperación organización y no podrán realizar determinadas acciones.

Cada ejercito tendrá reglas especiales que afectan a la cadena de mando. Por ejemplo, una compañía de la Wehrmacht del comienzo de la guerra donde los suboficiales están muy bien entrenados tendrá menos penalizadores para reflejar que cada escuadra opera mejor de forma independiente. Por el contrario, una compañía del ejército rojo tendrá un funcionamiento más rígido donde las escuadras que con una cadena de mando dañada sufrirán penalizaciones más severas.

== Keywords

Hay dos tipos de mando, el de los jefes de compañía y el de los jefes de sección. Los jefes de compañía pueden transmitir órdenes a cualquier unidad bajo su mando, mientras que los jefes de sección solo pueden transmitir órdenes a las unidades directamente bajo su mando.

=== HQ

`HQ {X} {Y}'`

* *X*: número máximo de secciones que puede administrar el jefe de compañía.
* *Y*: Distancia en pulgadas a las que el jefe está en mando con sus oficiales de sección.

La eliminación de un jefe de compañía afectará muy negativamente a toda la cadena de mando aplicando bonificadores a la reorganización, la moral y la capacidad de realizar determinadas maniobras.

=== Section Command

`Section Command {X} {Y}'`

* *X*: número máximo de modelos que que pueden estar en mando con el oficial de la sección.
* *Y*: Distancia en pulgadas a las que el jefe está en mando con sus oficiales de sección.

_Ejemplo, un Teniente con *Section Command 8 16'* haría que hasta 8 peanas de infantería a rango de 16 pulgadas se consideraran en cadena de mando._

Un jefe de sección deberá mantener la cadena de mando con el lider de la compañía para que sus unidades puedan beneficiarse de las órdenes del jefe de compañía. Si no es posible ya sea por la distancia o la eliminación de alguno de ellos las unidades bajo su mando tendrán diferentes penalizaciones.

TIP: Durante la partida muchos pelotones pueden haber perdido el contacto con su jefe de sección ya sea porque se han alejado o porque este ha causado baja. En estos casos otras unidades con Section Command pueden asumir el control de estas unidades. De este modo no se requiere establecer a nivel de miniaturas cual es la cadena de mando de cada una de ellas. Esta regla sólo aplica a unidades que sean del mismo tipo que la composición original. Un sargento de infantería no ofrecerá su mando a una sección de carros de combate por ejemplo.

=== Independent

`Independent`: esta keyword se aplicará a unidades que no se ven penalizadas por operar fuera de la cadena de mando, por ejemplo unidades de reconomiento, francotiradores, unidades de élite que operan de forma independiente, etc.

=== Radio

`RADIO`: esta keyword se aplicará a unidades que pueden recibir órdenes a través de radio, lo que les permite ignorar la distancia de mando.

== Restos de otras companías

Durante la creación de listas podemos añadir unidades que estén fuera de mando de la unidad principal. Por ejemplo una compañía de infantería que quiera introducir un par de Tiger I sin estar integrados dentro de la compañía.

De este modo podemos realizar listas más creativas (o más meta-game) sin tener que preocuparnos de una estructura rígida.

No obstante, estas unidades tendrán limitaciones al no estar bajo ninguna cadena de mando y tendrán más complicado realizar maniobras integradas dentro del resto de unidades. Actuarán más como lobos solitarios o requerirán de un esfuerzo adicional para que algún capitán coordine sus acciones, penalizando al resto de unidades bajo su mando.

== Notas de diseño

* La cadena de mando debe de ser uno de los elementos centrales dentro de la partida ya que determina la capacidad de una compañía para organizarse y reaccionar a los eventos del campo de batalla.

* Añade una capa de profundidad táctica que ofrece diferentes sabores de juego en función de ejércitos mas rígidos o mas flexibles.

* Ejércitos con radios se ven muy beneficiados ya que pueden permanecer en mando aunque sus unidades estén dispersas por el campo de batalla. Por ejemplo, una seccińo de 4 Tigers I con su comandante con radio podrá desplegar todas sus unidades en cualquier lugar del campo de batalla mientras que una sección de T-34-76 donde el comandante tiene que indicar las órdenes con banderas, bengalas o dando gritos tendrá que hacer que los tanques de la sección estén en un rango cercano.