= Turnos
:toc:
:toclevels: 3
:toc-title: Contenido

// WARNING: Considerar sistemas de activación simultánea.

WARNING: Considerar modelo sin turnos fijos para que la activación de ambos jugadores sea simultánea.

Cada turno representa una secuencia aproximada de 30 segundos de combate.

El turno se divide en varias fases:

* Fase de organización
//  (comprobar el estado de cada unidad afectada por el combate)
* Fase de activación
//  (declarar órdenes y acciones como cuerpo tierra, comunicación entre unidades para detectar unidades o solicitar apoyo de artillería)
* Fase de recuperación

NOTE: Como muchas unidades pueden tener diferentes interacciones con puntos de acción complejas de llevar podría estudiarse un sistema de activación simultáneo unidad por unidad en el que cuando seleccionas una unidad realiza todas las acciones (moral, acciones, movimiento, etc) hasta realizar la activación de la siguiente unidad.

== Fase de organización

En esta fase realizaremos las acciones de recuperación de organización, declaración de acciones de comandancia y otras acciones de mantenimiento de las unidades.

Los oficiales que puedan realizar acciones de mando aplicarán las bonificaciones de mando a las unidades bajo su control.

== Fase de activación

Esta es la fase principal donde iremos, unidad por unidad, declarando las acciones que va a realizar cada unidad presente durante la partida.

Para agilizar la partida, en lugar de tener una fase de movimiento, una fase de disparo, etc, realizaremos todas las acciones de una unidad durante su activación. Es decir, cuando seleccionamos una unidad, esta realizará todas las acciones que pueda realizar (mover, disparar, etc) y luego pasaremos a la siguiente unidad.

== Fase de recuperación

TODO: moral y demás

// En esta fase se aplicarán los efectos de las acciones realizadas durante la fase de activación, como el daño recibido, la supresión, etc. También se podrán realizar acciones de recuperación como reagruparse o reorganizarse para recuperar moral o reducir los efectos de la supresión.

