= Turnos
:toc:
:toclevels: 3
:toc-title: Contenido

Durante la partida cada jugador irá jugando su turno de forma alternada con el rival.

Los turnos se dividen en las siguientes fases:

- *Comandancia*
- *Movimiento*
- *Acciones*
- *Combate*

== Comandancia

En esta fase realizaremos las acciones de recuperación de organización, declaración de acciones de comandancia, chequeos de moral del ejército y otras acciones de mantenimiento de las unidades.

Los oficiales que puedan realizar acciones de mando aplicarán las bonificaciones de mando a las unidades bajo su control.

== Movimiento

En la fase de movimiento realizaremos el movimiento de todas la unidades que pudieran hacerlo.

== Acciones

En la fase de acciones cada unidad podrá declarar una acción diferente a la de combate. Estas acciones pueden ser por ejemplo solicitar apoyo de artillería, atrincherarse o declarar fuego de reacción.

== Combate

Durante la fase de disparo resolveremos todas las acciones de combate simultaneamente.
TODO: moral y demás

== Notas de diseño

Se podría agilizar el turno haciendo una activación completa de cada unidad (moviendo y disparando). No obstante esta opción hace que en función de los resultados del disparo las unidades realicen otra acción a la que hubieras previsto inicialmente y esto desvirtue la toma de decisiones.
