@startmindmap

' top to bottom direction

* Disparo
** Ligero
*** Impactar\n+ Balistic\n- Distance\n- Cover\n- Ambient\n+ Geometry
**** Herir\n+ Potencia ligera\n- Cover
***** Organización

** Pesado
*** Impactar\n(Balistic + Modifiers)
**** Penetrar\n+ AP\n- Blindaje\n- Distancia\n- Encaramiento
***** Efecto de penetración\n+ Potencia explosiva
****** Organización

** Blast
*** Impactar\n(Balistic + Modifiers)
**** Dispersión
***** Penetrar\n+ AP\n- Blindaje\n- Distancia\n- Encaramiento
****** Herir\n(Ligero/Pesado)
******* Organización

** Indirecto
*** Estimación
**** Dispersión
***** Efecto
****** Organización

legend
  [1]: La salvación de la infanteria es comun, la de otros elementos como armas
  remolcadas puede ser diferente.
  [2]: TODO
endlegend

@endmindmap
